config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals do
    member {post :toggle_completion}
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :user_id, :body, presence: true
  validates :private, inclusion: {in: [true, false]}

  belongs_to :user

  after_initialize :ensure_private, :ensure_completion_defaults_to_false

  def toggle_completion
    self.completed = !self.completed
    self.save!
  end

  private

  def ensure_private
    self.private ||= false
  end

  def ensure_completion_defaults_to_false
    self.completed ||= false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, uniqueness: true

  has_many :goals

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_cred(name, pass)
    user = User.find_by(username: name)
    return nil if user.nil?
    user.is_password?(pass) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest) == pass
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def log_in(user)
    session[:token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :ensure_logged_in
  before_action :redirect_if_not_owner, only: [:edit, :update]

  def index
    @goals = Goal.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to user_url(current_user)
    else
      flash[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to user_url(current_user)
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(current_user)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def toggle_completion
    @goal = Goal.find(params[:id])
    @goal.toggle_completion
    redirect_to user_url(@goal.user)
  end

  private

  def redirect_if_not_owner
   goal = Goal.find(params[:id])
   owner_id = goal.user_id
   redirect_to user_url(current_user) if owner_id != current_user.id
  end

  def goal_params
    params.require(:goal).permit([:user_id, :body, :private])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_cred(username_input, password_input)
    if @user
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["No matches for that password and username"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  private
  def username_input
    params[:user][:username]
  end

  def password_input
    params[:user][:password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      render :show
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit([:username, :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%=goal_url(@goal)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>Body
    <input id="Body" type="text" name="goal[body]" value="<%=@goal.body%>">
  </label>

  <label>Private
    <input type="checkbox" name="goal[private]" value="true">
  </label>

  <button>Update Goal</button>
</form>

app/views/goals/index.html.erb
<h1>All Goals</h1>

<ul>
  <% @goals.each do |goal| %>
    <% next if goal.private %>
    <li> <%= goal.body %> by <%= goal.user.username %> </li>
  <% end %>
</ul>

app/views/goals/new.html.erb
<h1>Create New Goal</h1>

<form action="<%=goals_url%>" method="post">
  <%= auth_token %>

  <label>Body
    <input id="Body" type="text" name="goal[body]">
  </label>

  <label>Private
    <input type="checkbox" name="goal[private]" value="true">
  </label>

  <button>Submit Goal</button>
</form>

app/views/goals/show.html.erb
<h1>Goals</h1>

<%= @goal.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%if logged_in?%>
    <%= current_user.username %>
    <form action="<%=session_url%>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <%=auth_token%>
      <button>Sign Out</button>
    </form>
  <%end%>

  <% if flash[:errors] %>
    <%flash[:errors].each do |error|%>
      <%=error%>
    <%end%>
  <%end%>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create User</h1>

<form action="<%=users_url%>" method="post">
  <%= auth_token %>

  <label>Username
    <input id="Username" type="text" name="user[username]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <button>Create User</button>
</form>

app/views/users/show.html.erb
<h1> <%= current_user.username %>'s Home Page</h1>

<ul>
  <% current_user.goals.each do |goal| %>
    <li>
      <%= goal.body %>
      <a href="<%= edit_goal_url(goal) %>">Edit Goal</a>
      <form action="<%= goal_url(goal) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <button>Delete Goal</button>
      </form>
      <%= goal.completed ? "Completed" : "Incomplete" %>
      <form action="<%=toggle_completion_goal_url(goal)%>" method="post">
        <%= auth_token %>
        <button>Toggle completion</button>
      </form>
    </li>
    <br><br>
  <% end %>
</ul>

<a href="<%= new_goal_url %>">Create New Goal</a>